Repository andrey-yantsen/plex-api.rs, pull requests merged in 2023-06, with the labels that each got.

#560 Update the media_container::server::Feature enum
  crates/plex-api/src/media_container/server/feature.rs
  crates/plex-api/tests/mocks/myplex/api/v2/features.json
Labels: C-Dependencies

#558 chore(main): release plex-api 0.0.11
  crates/plex-api/CHANGELOG.md
  crates/plex-api/Cargo.toml
Labels: autorelease: pending

#561 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#564 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#566 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#567 fix: Safer deserialisation for skip_parent and skip_count fields
  crates/plex-api/src/media_container/server/library/mod.rs
  crates/plex-api/tests/mocks/transcode/decision_13194.json
  crates/plex-api/tests/mocks/transcode/metadata_13194.json
  crates/plex-api/tests/transcode.rs
Labels: S-Run-Protected-Tests
