Repository andrey-yantsen/plex-api.rs, pull requests merged in 2023-03, with the labels that each got.

#516 feat: Add functionality for transcoding media.
  crates/plex-api/Cargo.toml
  crates/plex-api/src/error.rs
  crates/plex-api/src/http_client.rs
  crates/plex-api/src/lib.rs
  crates/plex-api/src/media_container/server/library.rs
  crates/plex-api/src/server/library.rs
  crates/plex-api/src/server/mod.rs
  crates/plex-api/src/server/transcode.rs
  crates/plex-api/src/url.rs
  crates/plex-api/src/webhook/mod.rs
  crates/plex-api/tests/mocks/transcode/empty_sessions.json
  crates/plex-api/tests/mocks/transcode/metadata_1036.json
  crates/plex-api/tests/mocks/transcode/metadata_157786.json
  crates/plex-api/tests/mocks/transcode/metadata_159637.json
  crates/plex-api/tests/mocks/transcode/music_mp3.json
  crates/plex-api/tests/mocks/transcode/music_sessions.json
  crates/plex-api/tests/mocks/transcode/video_dash_h264_mp3.json
  crates/plex-api/tests/mocks/transcode/video_dash_h265_aac.json
  crates/plex-api/tests/mocks/transcode/video_hls_vp9_pcm.json
  crates/plex-api/tests/mocks/transcode/video_offline_h264_mp3.json
  crates/plex-api/tests/mocks/transcode/video_offline_refused.json
  crates/plex-api/tests/mocks/transcode/video_sessions.json
  crates/plex-api/tests/transcode.rs
  crates/xtask/src/test.rs
Labels: C-Enhancement

#500 chore(main): release plex-api 0.0.6
  crates/plex-api/CHANGELOG.md
  crates/plex-api/Cargo.toml
Labels: autorelease: pending

#519 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#522 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#520 chore(main): release plex-api 0.0.7
  crates/plex-api/CHANGELOG.md
  crates/plex-api/Cargo.toml
Labels: autorelease: pending

#527 chore(main): release plex-api 0.0.8
  crates/plex-api/CHANGELOG.md
  crates/plex-api/Cargo.toml
Labels: autorelease: pending

#530 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#529 chore(main): release plex-api 0.0.9
  crates/plex-api/CHANGELOG.md
  crates/plex-api/Cargo.toml
Labels: autorelease: pending
