Repository andrey-yantsen/plex-api.rs, pull requests merged in 2023-05, with the labels that each got.

#548 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#554 Update the media_container::server::Feature enum
  crates/plex-api/src/media_container/server/feature.rs
  crates/plex-api/tests/mocks/myplex/api/v2/features.json
Labels: C-Dependencies

#532 chore(main): release plex-api 0.0.10
  crates/plex-api/CHANGELOG.md
  crates/plex-api/Cargo.toml
Labels: autorelease: pending

#504 chore(main): release plex-cli 0.0.3
  crates/plex-cli/CHANGELOG.md
  crates/plex-cli/Cargo.toml
Labels: autorelease: pending

#556 Update the list of tested PMS releases
  .github/mergify.yml
  .github/workflows/test.yml
  README.md
Labels: C-Dependencies

#557 fix!: Profile de-serialization when using new subtitle setting options
  crates/plex-api/src/myplex/account.rs
Labels: S-Run-Protected-Tests

#559 Update the media_container::server::Feature enum
  crates/plex-api/src/media_container/server/feature.rs
  crates/plex-api/tests/mocks/myplex/api/v2/features.json
Labels: C-Dependencies
